client/urls.py
from django.urls import path
from . import views

app_name = "client"
urlpatterns = [
    path('', views.index, name="Index"),
    path('shop', views.shop, name="Shop"),
    path('about', views.about, name="About"),
    path('services', views.services, name="Services"),
    path('blog', views.blog, name="Blog"),
    path('contact', views.contact, name="Contact"),
    path('cart', views.cart, name="Cart"),
    path('checkout', views.checkout, name="Checkout"),
    path('thankyou', views.thankyou, name="Thankyou"),
    path('singleblog/<id>', views.singleblog, name="Singleblog"),
    path('singleproduct/<id>', views.singleproduct, name="Singleproduct")

]

shop/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin', admin.site.urls),
    path('', include("client.urls"))
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
from django.utils import timezone


# Create your models here.

class Product(models.Model):
    name = models.CharField(max_length=60, blank=False, null=False)
    price = models.IntegerField()
    description = models.TextField()
    image = models.ImageField(upload_to="uploads/products", default="uploads/products/profile.png")

    def __str__(self):
        return self.name


class Testimonial(models.Model):
    name = models.CharField(max_length=60, blank=False, null=False)
    testimonial = models.TextField()
    post = models.CharField(max_length=150, blank=False, null=False)
    image = models.ImageField(upload_to="uploads/testimonials", default="uploads/testimonials/profile.png")

    def __str__(self):
        return self.name


class Blog(models.Model):
    title = models.CharField(max_length=60, blank=False, null=False)
    name = models.CharField(max_length=60, blank=False, null=False)
    image = models.ImageField(upload_to="uploads/blogs", default="uploads/blogs/profile.png")
    created_at = models.DateTimeField(default=timezone.now)
    content = models.TextField(null=False, default="Blog")

    def __str__(self):
        return self.title

client/views.py
from django.shortcuts import render
from .models import Product, Testimonial, Blog
from django.core.paginator import Paginator

def index(request):
    testimonial = Testimonial.objects.all()
    paginate_blog = Paginator(Blog.objects.all().order_by('name'), 3)
    page = request.GET.get('page')
    blogs = paginate_blog.get_page(page)

    paginate_product = Paginator(Product.objects.all().order_by('name'), 3)
    page_product = request.GET.get('page')
    product = paginate_product.get_page(page_product)
    return render(request, 'index.html', {'navbar': 'index', 'testimonial': testimonial, 'blogs':blogs, 'product': product})


def shop(request):
    product = Product.objects.all()
    return render(request, 'shop.html', {'navbar': 'shop', 'product': product})


def about(request):
    testimonial = Testimonial.objects.all()
    return render(request, 'about.html', {'navbar': 'about', 'testimonial': testimonial})


def services(request):
    testimonial = Testimonial.objects.all()

    paginate_product = Paginator(Product.objects.all().order_by('name'), 3)
    page_product = request.GET.get('page')
    product = paginate_product.get_page(page_product)
    return render(request, 'services.html', {'navbar': 'services', 'testimonial': testimonial, 'product': product})


def blog(request):
    testimonial = Testimonial.objects.all()
    blogs = Blog.objects.all()
    return render(request, 'blog.html', {'navbar': 'blog', 'testimonial': testimonial, 'blogs': blogs})


def contact(request):
    return render(request, 'contact.html', {'navbar': 'contact'})


def cart(request):
    return render(request, 'cart.html', {'navbar': 'cart'})


def checkout(request):
    return render(request, 'checkout.html', {'navbar': 'checkout'})


def thankyou(request):
    return render(request, 'thankyou.html')

def singleblog(request, id):
    singleblogpost = Blog.objects.get(id=id)
    return render(request, 'singleblog.html', {'singleblogpost': singleblogpost})

def singleproduct(request, id):
    singleproductpost = Product.objects.get(id=id)
    return render(request, 'singleproduct.html', {'singleproductpost': singleproductpost})

client/templates/cart.html
{% extends 'layout.html' %}
{% load static %}
{% block hero %}
    <h1>Cart</h1>
{% endblock %}
{% block section %}

    <title>Cart</title>

		

		<div class="untree_co-section before-footer-section">
            <div class="container">
              <div class="row mb-5">
                <form class="col-md-12" method="post">
                  <div class="site-blocks-table">
                    <table class="table">
                      <thead>
                        <tr>
                          <th class="product-thumbnail">Image</th>
                          <th class="product-name">Product</th>
                          <th class="product-price">Price</th>
                          <th class="product-quantity">Quantity</th>
                          <th class="product-total">Total</th>
                          <th class="product-remove">Remove</th>
                        </tr>
                      </thead>
                      <tbody>
                        <tr>
                          <td class="product-thumbnail">
                            <img src="{% static 'images/product-1.png' %}" alt="Image" class="img-fluid">
                          </td>
                          <td class="product-name">
                            <h2 class="h5 text-black">Product 1</h2>
                          </td>
                          <td>$49.00</td>
                          <td>
                            <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                              <div class="input-group-prepend">
                                <button class="btn btn-outline-black decrease" type="button">&minus;</button>
                              </div>
                              <input type="text" class="form-control text-center quantity-amount" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                              <div class="input-group-append">
                                <button class="btn btn-outline-black increase" type="button">&plus;</button>
                              </div>
                            </div>
        
                          </td>
                          <td>$49.00</td>
                          <td><a href="#" class="btn btn-black btn-sm">X</a></td>
                        </tr>
        
                        <tr>
                          <td class="product-thumbnail">
                            <img src="{% static 'images/product-2.png' %}" alt="Image" class="img-fluid">
                          </td>
                          <td class="product-name">
                            <h2 class="h5 text-black">Product 2</h2>
                          </td>
                          <td>$49.00</td>
                          <td>
                            <div class="input-group mb-3 d-flex align-items-center quantity-container" style="max-width: 120px;">
                              <div class="input-group-prepend">
                                <button class="btn btn-outline-black decrease" type="button">&minus;</button>
                              </div>
                              <input type="text" class="form-control text-center quantity-amount" value="1" placeholder="" aria-label="Example text with button addon" aria-describedby="button-addon1">
                              <div class="input-group-append">
                                <button class="btn btn-outline-black increase" type="button">&plus;</button>
                              </div>
                            </div>
        
                          </td>
                          <td>$49.00</td>
                          <td><a href="#" class="btn btn-black btn-sm">X</a></td>
                        </tr>
                      </tbody>
                    </table>
                  </div>
                </form>
              </div>
        
              <div class="row">
                <div class="col-md-6">
                  <div class="row mb-5">
                    <div class="col-md-6 mb-3 mb-md-0">
                      <button class="btn btn-black btn-sm btn-block">Update Cart</button>
                    </div>
                    <div class="col-md-6">
                      <button class="btn btn-outline-black btn-sm btn-block">Continue Shopping</button>
                    </div>
                  </div>
                  <div class="row">
                    <div class="col-md-12">
                      <label class="text-black h4" for="coupon">Coupon</label>
                      <p>Enter your coupon code if you have one.</p>
                    </div>
                    <div class="col-md-8 mb-3 mb-md-0">
                      <input type="text" class="form-control py-3" id="coupon" placeholder="Coupon Code">
                    </div>
                    <div class="col-md-4">
                      <button class="btn btn-black">Apply Coupon</button>
                    </div>
                  </div>
                </div>
                <div class="col-md-6 pl-5">
                  <div class="row justify-content-end">
                    <div class="col-md-7">
                      <div class="row">
                        <div class="col-md-12 text-right border-bottom mb-5">
                          <h3 class="text-black h4 text-uppercase">Cart Totals</h3>
                        </div>
                      </div>
                      <div class="row mb-3">
                        <div class="col-md-6">
                          <span class="text-black">Subtotal</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">$230.00</strong>
                        </div>
                      </div>
                      <div class="row mb-5">
                        <div class="col-md-6">
                          <span class="text-black">Total</span>
                        </div>
                        <div class="col-md-6 text-right">
                          <strong class="text-black">$230.00</strong>
                        </div>
                      </div>
        
                      <div class="row">
                        <div class="col-md-12">
                          <button class="btn btn-black btn-lg py-3 btn-block" onclick="window.location='{% url 'client:Checkout' %}'">Proceed To Checkout</button>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
		
{% endblock %}

client/templates/index.html
{% extends 'layout.html' %}
{% load static %}
{% block hero %}
        <h1>Modern Interior <span clsas="d-block">Design Studio</span></h1>

{% endblock %}
{% block image %}
    <img src="{% static 'images/couch.png' %}" class="img-fluid">
{% endblock %}
{% block section %}

    <title>Furni</title>


		<!-- Start Product Section -->
		<div class="product-section">
			<div class="container">
				<div class="row">

					<!-- Start Column 1 -->
					<div class="col-md-12 col-lg-3 mb-5 mb-lg-0">
						<h2 class="mb-4 section-title">Crafted with excellent material.</h2>
						<p class="mb-4">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. </p>
						<p><a href="{% url 'client:Shop' %}" class="btn">Explore</a></p>
					</div> 
					<!-- End Column 1 -->

					<!-- Start Column 2 -->
					 {% for product in product %}
					<div class="col-12 col-md-4 col-lg-3 mb-5">
						<a class="product-item" href="#">
							<img src="/media/{{ product.image }}" class="img-fluid product-thumbnail">
							<h3 class="product-title">{{ product.name}}</h3>
							<strong class="product-price">Ksh. {{ product.price }}</strong>

							<span class="icon-cross">
								<img src="{% static 'images/cross.svg' %}" class="img-fluid">
							</span>
						</a>
					</div>
                    {% endfor %}
					<!-- End Column 2 -->


				</div>
			</div>
		</div>
		<!-- End Product Section -->

		<!-- Start Why Choose Us Section -->
		<div class="why-choose-section">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-6">
						<h2 class="section-title">Why Choose Us</h2>
						<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>

						<div class="row my-5">
							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'images/truck.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Fast &amp; Free Shipping</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'images/bag.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Easy to Shop</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'images/support.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>24/7 Support</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

							<div class="col-6 col-md-6">
								<div class="feature">
									<div class="icon">
										<img src="{% static 'images/return.svg' %}" alt="Image" class="imf-fluid">
									</div>
									<h3>Hassle Free Returns</h3>
									<p>Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate.</p>
								</div>
							</div>

						</div>
					</div>

					<div class="col-lg-5">
						<div class="img-wrap">
							<img src="{% static 'images/why-choose-us-img.jpg' %}" alt="Image" class="img-fluid">
						</div>
					</div>

				</div>
			</div>
		</div>
		<!-- End Why Choose Us Section -->

		<!-- Start We Help Section -->
		<div class="we-help-section">
			<div class="container">
				<div class="row justify-content-between">
					<div class="col-lg-7 mb-5 mb-lg-0">
						<div class="imgs-grid">
							<div class="grid grid-1"><img src="{% static 'images/img-grid-1.jpg' %}" alt="Untree.co"></div>
							<div class="grid grid-2"><img src="{% static 'images/img-grid-2.jpg' %}" alt="Untree.co"></div>
							<div class="grid grid-3"><img src="{% static 'images/img-grid-3.jpg' %}" alt="Untree.co"></div>
						</div>
					</div>
					<div class="col-lg-5 ps-lg-5">
						<h2 class="section-title mb-4">We Help You Make Modern Interior Design</h2>
						<p>Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant morbi tristique senectus et netus et malesuada</p>

						<ul class="list-unstyled custom-list my-4">
							<li>Donec vitae odio quis nisl dapibus malesuada</li>
							<li>Donec vitae odio quis nisl dapibus malesuada</li>
							<li>Donec vitae odio quis nisl dapibus malesuada</li>
							<li>Donec vitae odio quis nisl dapibus malesuada</li>
						</ul>
						<p><a herf="#" class="btn">Explore</a></p>
					</div>
				</div>
			</div>
		</div>
		<!-- End We Help Section -->

		<!-- Start Popular Product -->
		<div class="popular-product">
			<div class="container">
				<div class="row">
                    {% for product in product %}
					<div class="col-12 col-md-6 col-lg-4 mb-4 mb-lg-0">
						<div class="product-item-sm d-flex">
							<div class="thumbnail">
								<img src="media/{{ product.image }}" alt="Image" class="img-fluid">
							</div>
							<div class="pt-3">
								<h3>{{ product.name }}</h3>
								<p>{{ product.description}}</p>
								<p><a href="/singleproduct/{{ product.id }}">Read More</a></p>
							</div>
						</div>
					</div>
                    {% endfor %}

				</div>
			</div>
		</div>
		<!-- End Popular Product -->

		<!-- Start Testimonial Slider -->
		<div class="testimonial-section">
			<div class="container">
				<div class="row">
					<div class="col-lg-7 mx-auto text-center">
						<h2 class="section-title">Testimonials</h2>
					</div>
				</div>

				<div class="row justify-content-center">
					<div class="col-lg-12">
						<div class="testimonial-slider-wrap text-center">

							<div id="testimonial-nav">
								<span class="prev" data-controls="prev"><span class="fa fa-chevron-left"></span></span>
								<span class="next" data-controls="next"><span class="fa fa-chevron-right"></span></span>
							</div>

							<div class="testimonial-slider">

                                {% for testimonial in testimonial %}
								
								<div class="item">
									<div class="row justify-content-center">
										<div class="col-lg-8 mx-auto">

											<div class="testimonial-block text-center">
												<blockquote class="mb-5">
													<p>&ldquo;{{ testimonial.testimonial }}&rdquo;</p>
												</blockquote>

												<div class="author-info">
													<div class="author-pic">
														<img src="media/{{ testimonial.image }}" alt="Maria Jones" class="img-fluid">
													</div>
													<h3 class="font-weight-bold">{{ testimonial.name }}</h3>
													<span class="position d-block mb-3">{{ testimonial.post }}</span>
												</div>
											</div>

										</div>
									</div>
								</div> 
								<!-- END item -->
                                {% endfor %}

							</div>

						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- End Testimonial Slider -->

		<!-- Start Blog Section -->
		<div class="blog-section">
			<div class="container">
				<div class="row mb-5">
					<div class="col-md-6">
						<h2 class="section-title">Recent Blog</h2>
					</div>
					<div class="col-md-6 text-start text-md-end">
						<a href="#" class="more">View All Posts</a>
					</div>
				</div>

				<div class="row">

					{% for blogs in blogs %}
					<div class="col-12 col-sm-6 col-md-4 mb-5">
						<div class="post-entry">
							<a href="#" class="post-thumbnail"><img src="media/{{ blogs.image }}" alt="Image" class="img-fluid"></a>
							<div class="post-content-entry">
								<h3><a href="#"> {{blogs.title}}</a></h3>
								<div class="meta">
									<span>by <a href="#">{{ blogs.name}}</a></span> <span>on <a href="#">{{ blogs.created_at}}</a></span>
								</div>
							</div>
						</div>
					</div>
                {% endfor %}


				</div>
			</div>
		</div>
		<!-- End Blog Section -->	

{% endblock %}

client/templates/layout.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="author" content="Untree.co">
  <link rel="shortcut icon" href="favicon.png">

  <meta name="description" content="" />
  <meta name="keywords" content="bootstrap, bootstrap4" />

		<!-- Bootstrap CSS -->
		<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css" rel="stylesheet">
		<link href="{% static 'css/tiny-slider.css' %}" rel="stylesheet">
		<link href="{% static 'css/style.css'%}" rel="stylesheet">
	</head>

	<body>

		<!-- Start Header/Navigation -->
		<nav class="custom-navbar navbar navbar navbar-expand-md navbar-dark bg-dark" arial-label="Furni navigation bar">

			<div class="container">
				<a class="navbar-brand" href="{% url 'client:Index' %}">Furni<span>.</span></a>

				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsFurni" aria-controls="navbarsFurni" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>

				<div class="collapse navbar-collapse" id="navbarsFurni">
					<ul class="custom-navbar-nav navbar-nav ms-auto mb-2 mb-md-0">
						<li class="nav-item">
							<a class="nav-link {% if navbar == 'index' %} active {% endif %}" href="{% url 'client:Index' %}">Home</a>
						</li>
						<li>
                            <a class="nav-link {% if navbar == 'shop' %} active {% endif %}" href="{% url 'client:Shop' %}">Shop</a>
                        </li>
						<li>
                            <a class="nav-link {% if navbar == 'about' %} active {% endif %}" href="{% url 'client:About' %}">About us</a>
                        </li>
						<li>
                            <a class="nav-link {% if navbar == 'services' %} active {% endif %}" href="{% url 'client:Services' %}">Services</a>
                        </li>
						<li>
                            <a class="nav-link {% if navbar == 'blog' %} active {% endif %}" href="{% url 'client:Blog' %}">Blog</a>
                        </li>
						<li>
                            <a class="nav-link {% if navbar == 'contact' %} active {% endif %}" href="{% url 'client:Contact' %}">Contact us</a>
                        </li>
					</ul>

					<ul class="custom-navbar-cta navbar-nav mb-2 mb-md-0 ms-5">
						<li><a class="nav-link" href="#"><img src="{% static 'images/user.svg' %}"></a></li>
						<li><a class="nav-link {% if navbar == 'cart' %} active {% endif %}" href="{% url 'client:Cart' %}"><img src="{% static 'images/cart.svg' %}"></a></li>
					</ul>
				</div>
			</div>

		</nav>
		<!-- End Header/Navigation -->
        		<!-- Start Hero Section -->
			<div class="hero">
				<div class="container">
					<div class="row justify-content-between">
						<div class="col-lg-5">
							<div class="intro-excerpt">
								{% block hero %}

                                {% endblock %}
                                <p class="mb-4">Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique.</p>
                                <p><a href="{% url 'client:Shop' %}" class="btn btn-secondary me-2">Shop Now</a><a href="{% url 'client:Shop' %}" class="btn btn-white-outline">Explore</a></p>
							</div>
						</div>
						<div class="col-lg-7">
							<div class="hero-img-wrap">
								{% block image %}

                                {% endblock %}
							</div>
						</div>
					</div>
				</div>
			</div>
		<!-- End Hero Section -->

        {% block section %}


        {% endblock %}

        <!-- Start Footer Section -->
		<footer class="footer-section">
			<div class="container relative">

				<div class="sofa-img">
					<img src="{% static 'images/sofa.png' %}" alt="Image" class="img-fluid">
				</div>

				<div class="row">
					<div class="col-lg-8">
						<div class="subscription-form">
							<h3 class="d-flex align-items-center"><span class="me-1"><img src="{% static 'images/envelope-outline.svg' %}" alt="Image" class="img-fluid"></span><span>Subscribe to Newsletter</span></h3>

							<form action="#" class="row g-3">
								<div class="col-auto">
									<input type="text" class="form-control" placeholder="Enter your name">
								</div>
								<div class="col-auto">
									<input type="email" class="form-control" placeholder="Enter your email">
								</div>
								<div class="col-auto">
									<button class="btn btn-primary">
										<span class="fa fa-paper-plane"></span>
									</button>
								</div>
							</form>

						</div>
					</div>
				</div>

				<div class="row g-5 mb-5">
					<div class="col-lg-4">
						<div class="mb-4 footer-logo-wrap"><a href="#" class="footer-logo">Furni<span>.</span></a></div>
						<p class="mb-4">Donec facilisis quam ut purus rutrum lobortis. Donec vitae odio quis nisl dapibus malesuada. Nullam ac aliquet velit. Aliquam vulputate velit imperdiet dolor tempor tristique. Pellentesque habitant</p>

						<ul class="list-unstyled custom-social">
							<li><a href="#"><span class="fa fa-brands fa-facebook-f"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-twitter"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-instagram"></span></a></li>
							<li><a href="#"><span class="fa fa-brands fa-linkedin"></span></a></li>
						</ul>
					</div>

					<div class="col-lg-8">
						<div class="row links-wrap">
							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="{% url 'client:About' %}">About us</a></li>
									<li><a href="{% url 'client:Services' %}">Services</a></li>
									<li><a href="{% url 'client:Blog' %}">Blog</a></li>
									<li><a href="{% url 'client:Contact' %}">Contact us</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Support</a></li>
									<li><a href="#">Knowledge base</a></li>
									<li><a href="#">Live chat</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Jobs</a></li>
									<li><a href="#">Our team</a></li>
									<li><a href="#">Leadership</a></li>
									<li><a href="#">Privacy Policy</a></li>
								</ul>
							</div>

							<div class="col-6 col-sm-6 col-md-3">
								<ul class="list-unstyled">
									<li><a href="#">Nordic Chair</a></li>
									<li><a href="#">Kruzo Aero</a></li>
									<li><a href="#">Ergonomic Chair</a></li>
								</ul>
							</div>
						</div>
					</div>

				</div>

				<div class="border-top copyright">
					<div class="row pt-4">
						<div class="col-lg-6">
							<p class="mb-2 text-center text-lg-start">Copyright &copy;<script>document.write(new Date().getFullYear());</script>. All Rights Reserved. &mdash; Designed with love by <a href="#">Group 3</a> Distributed By <a hreff="#">Microsoft Group 3</a>
            </p>
						</div>

						<div class="col-lg-6 text-center text-lg-end">
							<ul class="list-unstyled d-inline-flex ms-auto">
								<li class="me-4"><a href="#">Terms &amp; Conditions</a></li>
								<li><a href="#">Privacy Policy</a></li>
							</ul>
						</div>

					</div>
				</div>

			</div>
		</footer>
		<!-- End Footer Section -->


		<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
		<script src="{% static 'js/tiny-slider.js' %}"></script>
		<script src="{% static 'js/custom.js' %}"></script>
	</body>

</html>

client/templates/shop.html
{% extends 'layout.html' %}
{% load static %}
{% block hero %}
    <h1>Shop</h1>
{% endblock %}
{% block section %}

    <title>Shop</title>

		<div class="untree_co-section product-section before-footer-section">
		    <div class="container">
		      	<div class="row">

                    {% for product in product %}
					<div class="col-12 col-md-4 col-lg-3 mb-5">
						<a class="product-item" href="#">
							<img src="media/{{ product.image }}" class="img-fluid product-thumbnail" alt="{{ product.image }}">
							<h3 class="product-title">{{ product.name}}</h3>
							<strong class="product-price">Ksh. {{ product.price }}</strong>

							<span class="icon-cross">
								<img src="{% static 'images/cross.svg' %}" class="img-fluid">
							</span>
						</a>
					</div>
                    {% endfor %}
						


		      	</div>
		    </div>
		</div>


{% endblock %}

client/templates/thankyou.html
{% extends 'layout.html' %}
{% load static %}
{% block hero %}
    <h1>Cart</h1>
{% endblock %}
{% block section %}

    <title>Furni</title>


    <div class="untree_co-section">
        <div class="container">
          <div class="row">
            <div class="col-md-12 text-center pt-5">
              <span class="display-3 thankyou-icon text-primary">
                <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-cart-check mb-5" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
                  <path fill-rule="evenodd" d="M11.354 5.646a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L8 8.293l2.646-2.647a.5.5 0 0 1 .708 0z"/>
                  <path fill-rule="evenodd" d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .491.592l-1.5 8A.5.5 0 0 1 13 12H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l1.313 7h8.17l1.313-7H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 0 0 2 1 1 0 0 0 0-2zm7 0a1 1 0 1 0 0 2 1 1 0 0 0 0-2z"/>
                </svg>
              </span>
              <h2 class="display-3 text-black">Thank you!</h2>
              <p class="lead mb-5">You order was successfuly completed.</p>
              <p><a href="{% url 'client:Shop' %}" class="btn btn-sm btn-outline-black">Back to shop</a></p>
            </div>
          </div>
        </div>
    </div>

{% endblock %}